name: advanced_change_notifier
description: A ChangeNotfier alternative used to avoid redundant code .
version: 1.0.0

homepage: https://github.com/DerWolf01/advanced_change_notifier/blob/main/README.md
repository: https://github.com/DerWolf01/advanced_change_notifier/
environment:
  sdk: ^3.4.3


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
